[build-system]
requires = ["hatchling>=1.8.0"]
build-backend = "hatchling.build"

[project]
name = "FoxySheep"
version = "1.2.3"
description = "Mathematica parser and translator"
readme = "README.rst"
requires-python = ">=3.6"
license = { file = "LICENSE.txt" }
authors = [
  { name = "Robert Jacobson" }
]
classifiers = [
  "License :: OSI Approved :: BSD License",
  "Operating System :: OS Independent"
]
dependencies = [
  "antlr4-python3-runtime>=4.7,<4.8",
  "click>=7.1.2",
  "astor",
  "PyYAML",
  "astpretty"
]

[project.urls]
Homepage = "http://github.com/rocky/FoxySheep2"

[project.scripts]
foxy-sheep = "FoxySheep.__main__:main"

[project.optional-dependencies]
test = [
  "numpy",
  "pytest",
  "requests>=0.8.8",
  "mock>=1.0.1"
]
dev = [
  "numpy",
  "pytest",
  "tox>=4",
  "flake8"
]

[tool.hatch.build]
include = [
  "FoxySheep/**"
]
exclude = [
  "build/**",
  "dist/**",
  "FoxySheep.egg-info/**",
  "tools/**",
  "admin_tools/**"
]

[tool.flake8]
exclude = ".tox,build,trepan/processor/command/tmp"
filename = ["*.py"]
ignore = [
  "C901","E113","E121","E122","E123","E124","E125","E126","E127","E128","E129",
  "E201","E202","E203","E221","E222","E225","E226","E241","E242","E251","E261",
  "E271","E272","E302","E401","E501","F401","E701","E702","E731"
]

[tool.tox]
envlist = ["py26", "py27", "pypy"]

[tool.tox.testenv]
deps = ["requests>=0.8.8", "mock>=1.0.1"]
commands = ["python -W always -m pytest {posargs}"]

[tool.tox.testenv.py27]
deps = ["flake8"]
